# This file maps the variables to the appropriate UI fields
#
# Make sure to set default values for hidden required fields in the variables
# definition file

# Title shown in Application Information tab.
title: "Graph Studio in Autonomous Database"
# Sub Title shown in Application Information tab.
description: "Oracle Quickstart - Autonomous Database - Graph Studio Deployment stack"
schemaVersion: 1.1.0
version: "20220414"

# URL of Logo Icon used on Application Information tab. You can copy the contentId from the Marketplace listing logo URL in the Marketplace Partner portal.
# (Optional)

# logoUrl: "https://cloudmarketplace.oracle.com/marketplace/content?contentId=71472213"

# Used in Application Information tab to Hyperlink Title and Logo to the Marketplace
# Listing.
# Also used to link to Listing Usage section for "View Instructions".
# (Optional) If it is missing, Application Information uses the
# "marketplace-listing-id" tag for the same purpose.

# source:
#   type: marketplace
#   reference: 71472162
locale: "en"
variableGroups:
  - title: "Autonomous Database configuration"
    variables:
      - adb_compartment_ocid
      - adb_workload
      - adb_type
      - adb_cpu_core_count
      - adb_data_storage_size_in_tbs
      - adb_enable_auto_scale
      - adb_license_model
      - adb_name
      - adb_version_adw
      - adb_version_atp

  - title: "Network configuration"
    visible:
      eq:
        - adb_type
        - "Paid Oracle Autonomous Database"
    variables:
      - access_type
      - network_compartment_id
      - vcn_strategy
      - existing_vcn_id
      - vcn_name
      - vcn_cidr
      - subnet_cidr
      - subnet_id
      - nsg_strategy
      - nsg_label
      - use_existing_nsg

  - title: "Bastion configuration"
    visible:
      eq:
        - access_type
        - "Private endpoint access only"
    variables:
      - bastion_name
      - cidr_allowlist
      - max_ttl
      - ssh_public_key

  - title: "Tags"
    variables:
      - show_tag_options
      - defined_tag

  - title: "Hidden variables"
    visible: false #"variables used internally - not exposed to end user"
    variables:
      - tenancy_ocid
      - region
      - compartment_ocid
      - admin_pwd
      - adb_type_enum
      - adb_license_model_enum
      - adb_workload_enum
      - user_id
      - fingerprint
      - private_key_path
      - access_type_enum
      - nsg_strategy_enum
      - vcn_strategy_enum

variables:

  # Database variables
  adb_compartment_ocid:
    type: oci:identity:compartment:id
    required: true
    title: Autonomous Database compartment
    description: The compartment in which to create or find the database resources
    default: compartment_ocid

  adb_workload:
    type: enum
    required: true
    enum: 
      - "Data Warehouse (Serverless Infrastructure)"
      - "Transaction Processing (Serverless Infrastructure)"
    default: "Data Warehouse (Serverless Infrastructure)"
    title: Autonomous Database Workload

  adb_type:
    type: enum
    enum:
      - "Always Free Oracle Autonomous Data Warehouse (1 OCPU 20 GB Storage)"
      - "Paid Oracle Autonomous Database"
    title: Database Type
    required: true
    default: "Paid Oracle Autonomous Database"

  adb_cpu_core_count:
    visible:
      eq:
        - adb_type
        - "Paid Oracle Autonomous Database"
    type: integer
    minimum: 2
    maximum: 512
    multipleOf: 1
    title: The number of ECPU cores to be made available to the database
    description: The number of ECPU cores to enable. Available cores are subject to your tenancy's service limits
    required: true

  adb_data_storage_size_in_tbs:
    visible:
      eq:
        - adb_type
        - "Paid Oracle Autonomous Database"
    type: number
    minimum: 1
    maximum: 384
    multipleOf: 1
    title: The quantity of data in the database, in terabytes
    description: The amount of storage to allocate
    required: true

  adb_enable_auto_scale:
    visible:
      eq:
        - adb_type
        - "Paid Oracle Autonomous Database"
    type: boolean
    title: Enable auto scaling for the Autonomous Data Warehouse CPU core count
    required: true

  adb_license_model:
    visible:
      eq:
        - adb_type
        - "Paid Oracle Autonomous Database"
    type: enum
    title: "Database license type"
    description: "Select to subscribe to new Oracle database software license or bring your organization's Oracle database software license"
    required: true
    enum:
    #   - "LICENSE_INCLUDED"
    #   - "BRING_YOUR_OWN_LICENSE"
    # default: "LICENSE_INCLUDED"
      - "Bring Your Own License (BYOL)"
      - "License Included"
    default: "License Included"

  adb_name:
    type: string
    title: "Database name"
    description: "The name for the Autonomous Database instance. The deployment id (4 characters random string) will be added to the end of the DB name."
    minLength: 1
    maxLength: 10
    pattern: "^[a-zA-Z][a-zA-Z0-9]+$"
    required: true

  adb_version_adw:
    visible: 
      eq:
        - adb_workload
        - "Data Warehouse (Serverless Infrastructure)"
    type: oci:database:autonomousdatabaseversion:id
    title: "Database version"
    description: "The available Autonomous Data Warehouse versions"
    required: true
    default: "19c"
    dependsOn:
      compartmentId: adb_compartment_ocid
      dbWorkload: "DW"

  adb_version_atp:
    visible: 
      eq:
        - adb_workload
        - "Transaction Processing (Serverless Infrastructure)"
    type: oci:database:autonomousdatabaseversion:id
    title: "Database version"
    description: "The available Autonomous Transaction Processing versions"
    required: true
    default: "19c"
    dependsOn:
      compartmentId: adb_compartment_ocid
      dbWorkload: "OLTP"

  # Network Configuration
  access_type:
    type: enum
    title: "Database access type"
    description: "Choose network access"
    enum:
      - "Private endpoint access only"
      - "Secure access from everywhere"
    default: "Private endpoint access only"
    required: true

  network_compartment_id:
    visible:
      eq:
        - access_type
        - "Private endpoint access only"
    type: oci:identity:compartment:id
    title: Network Compartment
    description: The compartment to select the existing <a target="_blank" href="https://docs.cloud.oracle.com/iaas/Content/Network/Concepts/overview.htm">network</a>.
    required: true
    default: compartment_ocid

  vcn_strategy:
    visible:
      eq:
        - access_type
        - "Private endpoint access only"
    type: enum
    title: Virtual Cloud Network Strategy
    description: Create or use existing VCN
    enum:
      - "Create New VCN"
      - "Use Existing VCN"
    required: true
    default: "Create New VCN"

  vcn_name:
    visible:
      and:
        - eq:
          - access_type
          - "Private endpoint access only"
        - eq:
          - vcn_strategy
          - "Create New VCN"
    type: string
    default: "graphsvcn"
    minLength: 1
    maxLength: 255
    pattern: "^[a-zA-Z_]\\w{0,254}$"
    required: true
    title: Database Network Name
    description: The name for the new Virtual Cloud Network (VCN) to create for this service.

  vcn_cidr:
    visible:
      and:
        - eq:
          - access_type
          - "Private endpoint access only"
        - eq:
          - vcn_strategy
          - "Create New VCN"
    type: string
    default: 10.0.0.0/16
    required: true
    pattern: "^(25[0-5]|2[0-4][0-9]|1[0-9][0-9]|[1-9]?[0-9]).(25[0-5]|2[0-4][0-9]|1[0-9][0-9]|[1-9]?[0-9]).(25[0-5]|2[0-4][0-9]|1[0-9][0-9]|[1-9]?[0-9]).(25[0-5]|2[0-4][0-9]|1[0-9][0-9]|[1-9]?[0-9])\\/(3[0-2]|[1-2]?[0-9])$"
    title: Database Network CIDR
    description: "The CIDR to assign to the new Virtual Cloud Network (VCN) for this service. The new VCN's CIDR should not overlap with any other existing VCN CIDR. Example: 10.0.0.0/16"

  subnet_cidr:
    visible:
      and:
        - eq:
          - access_type
          - "Private endpoint access only"
        - eq:
          - vcn_strategy
          - "Create New VCN"
    type: string
    default: 10.0.1.0/24
    pattern: "^(25[0-5]|2[0-4][0-9]|1[0-9][0-9]|[1-9]?[0-9]).(25[0-5]|2[0-4][0-9]|1[0-9][0-9]|[1-9]?[0-9]).(25[0-5]|2[0-4][0-9]|1[0-9][0-9]|[1-9]?[0-9]).(25[0-5]|2[0-4][0-9]|1[0-9][0-9]|[1-9]?[0-9])\\/(3[0-2]|[1-2]?[0-9])$"
    required: true
    title: Private Subnet CIDR
    description: "The CIDR of the new Private Regional subnet for the database instance. The new subnet's CIDR should not overlap with any other subnet CIDRs. Example: 10.0.1.0/24"

  existing_vcn_id:
    visible:
      and:
        - eq:
          - access_type
          - "Private endpoint access only"
        - eq:
          - vcn_strategy
          - "Use Existing VCN"
    type: oci:core:vcn:id
    dependsOn:
      compartmentId: network_compartment_id
    required: true
    default: ''
    title: Existing Network
    description: An existing Virtual Cloud Network (VCN).

  subnet_id:
    visible:
      and:
        - eq:
          - access_type
          - "Private endpoint access only"
        - eq:
          - vcn_strategy
          - "Use Existing VCN"
    type: oci:core:subnet:id
    dependsOn:
      vcnId: existing_vcn_id
      compartmentId: network_compartment_id
      hidePublicSubnet: true
    default: ''
    required: true
    title: Existing Private Subnet
    description: "Select an existing subnet to use for the database."

  nsg_strategy:
    visible:
      eq:
        - access_type
        - "Private endpoint access only"
    type: enum
    enum:
      - "Create a new NSG"
      - "Use an existing NSG"
    default: "Create a new NSG"
    required: true
    title: Attach Network Security Group
    description: Attach a Network Security Group to the database to allow Bastion access.

  nsg_label:
    visible:
      and:
        - eq:
          - nsg_strategy
          - "Create a new NSG"
        - eq:
          - access_type
          - "Private endpoint access only"
    title: Network Security Group name
    description: A descriptive name to help you keep track of your network security groups.
    minLength: 1
    maxLength: 30
    pattern: "^[a-zA-Z][a-zA-Z0-9]+"
    required: true

  use_existing_nsg:
    type: oci:core:nsg:id
    visible:
      and:
        - eq:
          - nsg_strategy
          - "Use an existing NSG"
        - eq:
          - access_type
          - "Private endpoint access only"
    title: Network Security Group
    required: true
    description: Select an existing network security group to attach to the database, make sure the corresponding rule exists to allow Bastion Service access.
    dependsOn:
      compartmentId: network_compartment_id

  # Bastion
  bastion_name:
    type: string
    title: Bastion name
    default: graphDBBastion
    required: true

  cidr_allowlist:
    type: array
    items:
      type: string
    title: CIDR block allowlist
    description: "Example: 11.0.0.0/24 The IP address range that you want to allow to connect to target resources through SSH connections created through sessions hosted by this bastion."
    pattern: "^(25[0-5]|2[0-4][0-9]|1[0-9][0-9]|[1-9]?[0-9]).(25[0-5]|2[0-4][0-9]|1[0-9][0-9]|[1-9]?[0-9]).(25[0-5]|2[0-4][0-9]|1[0-9][0-9]|[1-9]?[0-9]).(25[0-5]|2[0-4][0-9]|1[0-9][0-9]|[1-9]?[0-9])\\/(3[0-2]|[1-2]?[0-9])$"
    default: [0.0.0.0/0]
    required: true
    
  max_ttl:
    type: integer
    title: Maximum session time-to-live (TTL) minutes
    description: The maximum session time-to-live sets an upper limit for the length of time any session created on this bastion can be used to connect to a target host.
    default: 180
    minimum: 30
    maximum: 180
    multipleOf: 1
    required: true

  ssh_public_key:
    type: oci:core:ssh:publickey
    title: SSH Public Key
    description: Bastion sessions use an <a target="_blank" href="https://docs.cloud.oracle.com/iaas/Content/Compute/Tasks/managingkeypairs.htm">SSH key pair</a> instead of a password to authenticate remote users. Generate a key pair and upload your own public key now. When you <a target="_blank" href="https://docs.oracle.com/en-us/iaas/Content/Bastion/Tasks/create-session-managed-ssh.htm">connect to the Bastion</a>, you will provide the associated private key.
    required: true
    pattern: "((^(ssh-rsa AAAAB3NzaC1yc2|ecdsa-sha2-nistp256 AAAAE2VjZHNhLXNoYTItbmlzdHAyNT|ecdsa-sha2-nistp384 AAAAE2VjZHNhLXNoYTItbmlzdHAzODQAAAAIbmlzdHAzOD|ecdsa-sha2-nistp521 AAAAE2VjZHNhLXNoYTItbmlzdHA1MjEAAAAIbmlzdHA1Mj|ssh-ed25519 AAAAC3NzaC1lZDI1NTE5|ssh-dss AAAAB3NzaC1kc3)[0-9A-Za-z+\/]+[=]{0,3})( [^,]*)?)(,((ssh-rsa AAAAB3NzaC1yc2|ecdsa-sha2-nistp256 AAAAE2VjZHNhLXNoYTItbmlzdHAyNT|ecdsa-sha2-nistp384 AAAAE2VjZHNhLXNoYTItbmlzdHAzODQAAAAIbmlzdHAzOD|ecdsa-sha2-nistp521 AAAAE2VjZHNhLXNoYTItbmlzdHA1MjEAAAAIbmlzdHA1Mj|ssh-ed25519 AAAAC3NzaC1lZDI1NTE5|ssh-dss AAAAB3NzaC1kc3)[0-9A-Za-z+\/]+[=]{0,3})( [^,]*)?)*$"


  # Tagging variables
  show_tag_options:
    type: boolean
    title: Enable tagging for the resources
    description: Enable tagging for the resources created in this stack.

  defined_tag:
    visible: show_tag_options
    type: oci:identity:tag:value
    title: Tagging


  # Hidden Variables
  tenancy_ocid:
    type: string
    title: Tenancy ID
    description: The Oracle Cloud Identifier (OCID) for your tenancy
    required: true

  region:
    type: oci:identity:region:name
    title: Region
    description: The region in which to create all resources
    required: true

  compartment_ocid:
    type: oci:identity:compartment:id
    title: Instance server compartment
    description: The compartment in which to create the server compute instances
    required: true

  user_id:
    type: string

  private_key_path:
    type: string

  fingerprint:
    type: string

outputGroups:
  - title: Notes
    outputs:
      - notes
  - title: Database details
    outputs:
      - adb_id
      - adb_name
      - adb_admin_password
      - dashboard_url
  - title: Graph details
    outputs: 
      - graph_username
      - graph_password
  - title: Connection details
    outputs:
      - connect
      - private_endpoint

outputs:
  dashboard_url:
    type: link
    title: Graph Studio URL

  adb_id:
    type: ocid
    title: Autonomous Database OCID
    visible: true

  adb_name:
    type: string
    title: Database Name
    visible: true

  adb_admin_password:
    type: string
    title: Database admin password
    displayText: Autonomous Database admin password
    sensitive: true
    visible: true

  graph_username:
    type: copyableString
    title: Graph Username
    visible: true

  graph_password:
    type: copyableString
    title: Graph Password
    sensitive: true

  notes:
    type: string
    title: Notes
    visible: true
  
  connect:
    type: string
    title: SSH command
    visible: true

  private_endpoint:
    type: copyableString
    title: Private Endpoint
    visible: true

#primaryOutputButton: dashboard_url
