# This file maps the variables to the appropriate UI fields
#
# Make sure to set default values for hidden required fields in the variables
# definition file

# Title shown in Application Information tab.
title: "Graph Studio in Autonomous Database"
# Sub Title shown in Application Information tab.
description: "Oracle Quickstart - Autonomous Database - Graph Studio Deployment stack"
schemaVersion: 1.1.0
version: "20220414"

# URL of Logo Icon used on Application Information tab. You can copy the contentId from the Marketplace listing logo URL in the Marketplace Partner portal.
# (Optional)

# logoUrl: "https://cloudmarketplace.oracle.com/marketplace/content?contentId=71472213"

# Used in Application Information tab to Hyperlink Title and Logo to the Marketplace
# Listing.
# Also used to link to Listing Usage section for "View Instructions".
# (Optional) If it is missing, Application Information uses the
# "marketplace-listing-id" tag for the same purpose.

# source:
#   type: marketplace
#   reference: 71472162
locale: "en"
variableGroups:
  - title: "Autonomous Database configuration"
    variables:
      - adb_compartment_ocid
      - adb_workload
      - adb_type
      - adb_cpu_core_count
      - adb_data_storage_size_in_tbs
      - adb_enable_auto_scale
      - adb_license_model
      - adb_name
      - adb_version

  - title: "Tags"
    variables:
      - show_tag_options
      - defined_tag

  - title: "Hidden variables"
    visible: false #"variables used internally - not exposed to end user"
    variables:
      - tenancy_ocid
      - region
      - compartment_ocid
      - adb_type_enum
      - adb_license_model_enum
      - adb_workload_enum
      - user_id
      - fingerprint
      - private_key_path

variables:

  # Database variables
  adb_compartment_ocid:
    type: oci:identity:compartment:id
    required: true
    title: Autonomous Database compartment
    description: The compartment in which to create or find the database resources
    default: compartment_ocid

  adb_workload:
    type: enum
    required: true
    enum:
      - "Autonomous Transaction Processing"
      - "Autonomous Data Warehouse"
    title: Autonomous Database Workload
    default: "Autonomous Transaction Processing"

  adb_type:
    type: enum
    enum:
      - "Always Free Oracle Autonomous Data Warehouse (1 OCPU 20 GB Storage)"
      - "Paid Oracle Autonomous Database"
    title: Database Type
    required: true
    default: "Paid Oracle Autonomous Database"

  adb_cpu_core_count:
    visible:
      eq:
        - adb_type
        - "Paid Oracle Autonomous Database"
    type: integer
    minimum: 1
    maximum: 128
    multipleOf: 1
    title: The number of OCPU cores to be made available to the database
    description: The number of OCPU cores to enable. Available cores are subject to your tenancy's service limits
    required: true

  adb_data_storage_size_in_tbs:
    visible:
      eq:
        - adb_type
        - "Paid Oracle Autonomous Database"
    type: number
    minimum: 1
    maximum: 128
    multipleOf: 1
    title: The quantity of data in the database, in terabytes
    description: The amount of storage to allocate
    required: true

  adb_enable_auto_scale:
    visible:
      eq:
        - adb_type
        - "Paid Oracle Autonomous Database"
    type: boolean
    title: Enable auto scaling for the Autonomous Data Warehouse CPU core count
    required: true

  adb_license_model:
    visible:
      eq:
        - adb_type
        - "Paid Oracle Autonomous Database"
    type: enum
    title: "Database license type"
    description: "Select to subscribe to new Oracle database software license or bring your organization's Oracle database software license"
    required: true
    enum:
    #   - "LICENSE_INCLUDED"
    #   - "BRING_YOUR_OWN_LICENSE"
    # default: "LICENSE_INCLUDED"
      - "Bring Your Own License (BYOL)"
      - "License Included"
    default: "License Included"

  adb_name:
    type: string
    title: "Database name"
    description: "The name for the Autonomous Database instance. The deployment id (4 characters random string) will be added to the end of the DB name."
    minLength: 1
    maxLength: 10
    pattern: "^[a-zA-Z][a-zA-Z0-9]+$"
    required: true

  adb_version:
    type: oci:database:autonomousdatabaseversion:id
    title: "Database version"
    description: "The available Autonomous Database versions"
    required: true
    enum: 
      - "19c"
      - "21c"
    default: "19c"
    dependsOn:
      compartmentId: ${adb_compartment_ocid}
      dbWorkload: "OLTP"

  # Tagging variables
  show_tag_options:
    type: boolean
    title: Enable tagging for the resources
    description: Enable tagging for the resources created in this stack.

  defined_tag:
    visible: show_tag_options
    type: oci:identity:tag:value
    title: Tagging


  # Hidden Variables
  tenancy_ocid:
    type: string
    title: Tenancy ID
    description: The Oracle Cloud Identifier (OCID) for your tenancy
    required: true

  region:
    type: oci:identity:region:name
    title: Region
    description: The region in which to create all resources
    required: true

  compartment_ocid:
    type: oci:identity:compartment:id
    title: Instance server compartment
    description: The compartment in which to create the server compute instances
    required: true

  user_id:
    type: string

  private_key_path:
    type: string

  fingerprint:
    type: string

outputGroups:
  - title: Database details
    outputs:
      - adb_id
      - adb_name
      - adb_admin_password
  - title: Graph details
    outputs: 
      - graph_username
      - graph_password

outputs:
  dashboard_url:
    type: link
    title: Open Graph Studio
    visible: false

  adb_id:
    type: ocid
    title: Autonomous Database OCID
    visible: true

  adb_name:
    type: string
    title: Database Name
    visible: true

  adb_admin_password:
    type: string
    title: Database admin password
    displayText: Autonomous Database admin password
    sensitive: true

  graph_username:
    type: string
    title: Graph Username
    visible: true

  graph_password:
    type: copyableString
    title: Graph Password
    sensitive: false

  notes:
    type: string
    title: Notes
    visible: true

primaryOutputButton: dashboard_url
